### PR TITLE
Start docs

### PR DESCRIPTION
**Pull request by inducer**

### CODE REVIEW

**Comment by inducer** [comment]
@ecisneros8 Here are my changes to get the docs going. I'll merge this so that I can get ReadTheDocs configured. But feel free to add comments/questions on this PR.

**Comment by inducer** [comment]
Oh, heh. Spoke too soon. I can't merge without your approval.

**Comment by inducer** [comment]
Maybe you should configure https://readthedocs.io anyway, so that you have control.

**Review by ecisneros8 — APPROVED** [review]
Looks good. Thanks!

**Pull request merged**
